version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_TYPE=postgres
      - DB_USER=root
      - DB_PASS=passWord123$$$$$$
      - DB_HOST=algolyticdb.cy07c5le73ah.ap-south-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_DB=postgres
      - PORT=4000

    ports:
      - 4000:4000