name: PingTest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_TYPE: postgres
      DB_USER: root
      DB_PASS: passWord123$$$
      DB_HOST: algolyticdb.cy07c5le73ah.ap-south-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_DB: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test